spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ucoursescourseall@gmail.com
    password: Usecourse9876@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

